/**
 * @jest-environment jsdom
 */

import { describe, test, expect, jest, beforeEach, afterEach } from '@jest/globals';
import { uiBuilder, UIBuilder } from '../ui-builder.js';

describe('UI Builder Extended Tests', () => {
    let container: HTMLElement;

    beforeEach(() => {
        container = document.createElement('div');
        container.id = 'calculator-container';
        document.body.appendChild(container);
    });

    afterEach(() => {
        document.body.innerHTML = '';
        jest.restoreAllMocks();
    });

    // =========================================================================
    // 1. generateReport()
    // =========================================================================
    describe('generateReport', () => {
        test('returns empty string when container does not exist', () => {
            document.body.innerHTML = '';
            const report = uiBuilder.generateReport('nonexistent-container');
            expect(report).toBe('');
        });

        test('generates report header with page title and patient info', () => {
            // Set up page title
            const titleEl = document.createElement('h1');
            titleEl.id = 'page-title';
            titleEl.textContent = 'BMI Calculator';
            document.body.appendChild(titleEl);

            // Set up patient info
            const patientEl = document.createElement('div');
            patientEl.id = 'patient-info';
            patientEl.innerText = 'Patient: John Doe';
            document.body.appendChild(patientEl);

            const report = uiBuilder.generateReport();

            expect(report).toContain('*** BMI Calculator ***');
            expect(report).toContain('Patient: John Doe');
            expect(report).toContain('Date:');
            expect(report).toContain('Generated by: CGMH EHRCALC');
        });

        test('uses default title and patient info when elements are missing', () => {
            const report = uiBuilder.generateReport();

            expect(report).toContain('*** Calculator Report ***');
            expect(report).toContain('Patient: Unknown');
        });

        test('includes checked radio button values with group label', () => {
            container.innerHTML = `
                <div class="ui-input-group">
                    <label>Gender</label>
                    <div class="ui-radio-group">
                        <div class="ui-radio-option">
                            <input type="radio" id="gender-m" name="gender" value="male">
                            <label for="gender-m" class="radio-label">Male</label>
                        </div>
                        <div class="ui-radio-option">
                            <input type="radio" id="gender-f" name="gender" value="female" checked>
                            <label for="gender-f" class="radio-label">Female</label>
                        </div>
                    </div>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('Gender: Female');
        });

        test('includes checked checkbox values with group label', () => {
            container.innerHTML = `
                <div class="ui-input-group">
                    <label>Risk Factors</label>
                    <div class="ui-checkbox-group">
                        <div class="ui-checkbox-option">
                            <input type="checkbox" id="rf-1" name="risk" value="smoking" checked>
                            <label for="rf-1" class="checkbox-label">Smoking</label>
                        </div>
                        <div class="ui-checkbox-option">
                            <input type="checkbox" id="rf-2" name="risk" value="diabetes">
                            <label for="rf-2" class="checkbox-label">Diabetes</label>
                        </div>
                    </div>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('Risk Factors: Smoking');
            // Unchecked checkbox should NOT appear
            expect(report).not.toContain('Diabetes');
        });

        test('radio without group label falls back to section title', () => {
            container.innerHTML = `
                <div class="ui-section">
                    <div class="ui-section-title">Clinical Assessment</div>
                    <div class="ui-radio-option">
                        <input type="radio" id="grade-1" name="grade" value="1" checked>
                        <label for="grade-1" class="radio-label">Grade I</label>
                    </div>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('Clinical Assessment: Grade I');
        });

        test('radio without group label falls back to section subtitle if no title', () => {
            container.innerHTML = `
                <div class="ui-section">
                    <div class="ui-section-subtitle">Severity Level</div>
                    <div class="ui-radio-option">
                        <input type="radio" id="sev-1" name="severity" value="mild" checked>
                        <label for="sev-1" class="radio-label">Mild</label>
                    </div>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('Severity Level: Mild');
        });

        test('checked radio/checkbox with no group/section label uses fallback format', () => {
            container.innerHTML = `
                <div class="ui-checkbox-option">
                    <input type="checkbox" id="solo-check" value="yes" checked>
                    <label for="solo-check" class="checkbox-label">Agree</label>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('[x] Agree');
        });

        test('includes normal text/number input values with labels', () => {
            container.innerHTML = `
                <div class="ui-input-group">
                    <label for="age-input">Age</label>
                    <input id="age-input" type="number" value="45">
                </div>
                <div class="ui-input-group">
                    <label for="weight-input">Weight</label>
                    <input id="weight-input" type="number" value="70">
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('Age: 45');
            expect(report).toContain('Weight: 70');
        });

        test('skips inputs with empty values', () => {
            container.innerHTML = `
                <div class="ui-input-group">
                    <label for="empty-input">Empty Field</label>
                    <input id="empty-input" type="text" value="">
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).not.toContain('Empty Field:');
        });

        test('skips button and submit type inputs', () => {
            container.innerHTML = `
                <input type="button" value="Click">
                <input type="submit" value="Submit">
            `;

            const report = uiBuilder.generateReport();
            expect(report).not.toContain('Click');
            expect(report).not.toContain('Submit');
        });

        test('includes select values', () => {
            container.innerHTML = `
                <div class="ui-input-group">
                    <label for="unit-select">Unit</label>
                    <select id="unit-select">
                        <option value="metric" selected>Metric</option>
                        <option value="imperial">Imperial</option>
                    </select>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('Unit: metric');
        });

        test('includes result items with label and value', () => {
            container.innerHTML = `
                <div class="ui-result-score">
                    <div class="ui-result-label">BMI</div>
                    <div class="ui-result-value">22.5<span class="ui-result-unit">kg/m2</span></div>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('--- RESULTS ---');
            expect(report).toContain('BMI:');
        });

        test('includes result items without label', () => {
            container.innerHTML = `
                <div class="ui-result-score">
                    <div class="ui-result-value">42</div>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('42');
        });

        test('includes interpretation sections', () => {
            container.innerHTML = `
                <div class="ui-result-interpretation success">Normal weight range</div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('Interpretation: Normal weight range');
        });

        test('handles input with id but no matching label element', () => {
            container.innerHTML = `
                <input id="orphan-input" type="text" value="test-value">
            `;

            const report = uiBuilder.generateReport();
            // Should fall back to using the id as the label
            expect(report).toContain('orphan-input: test-value');
        });

        test('handles input without id', () => {
            container.innerHTML = `
                <input type="text" value="anonymous-value">
            `;

            const report = uiBuilder.generateReport();
            // Falls back to 'Unknown Field'
            expect(report).toContain('Unknown Field: anonymous-value');
        });

        test('uses default container id when no argument is passed', () => {
            container.innerHTML = `
                <div class="ui-input-group">
                    <label for="test-def">Field</label>
                    <input id="test-def" type="number" value="99">
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('Field: 99');
        });

        test('handles ui-result-item class in addition to ui-result-score', () => {
            container.innerHTML = `
                <div class="ui-result-item">
                    <div class="ui-section-subtitle">CrCl</div>
                    <div class="ui-result-value">120<span class="ui-result-unit">mL/min</span></div>
                </div>
            `;

            const report = uiBuilder.generateReport();
            expect(report).toContain('CrCl:');
        });
    });

    // =========================================================================
    // 2. createForm()
    // =========================================================================
    describe('createForm', () => {
        test('routes text type to createInput', () => {
            const html = uiBuilder.createForm({
                fields: [
                    { type: 'text', id: 'name-input', label: 'Name', placeholder: 'Enter name' }
                ]
            });

            expect(html).toContain('<form');
            expect(html).toContain('name-input');
            expect(html).toContain('Name');
            expect(html).toContain('type="text"');
        });

        test('routes number type to createInput', () => {
            const html = uiBuilder.createForm({
                fields: [
                    { type: 'number', id: 'age-input', label: 'Age', min: 0, max: 150 }
                ]
            });

            expect(html).toContain('age-input');
            expect(html).toContain('type="number"');
        });

        test('routes input type to createInput', () => {
            const html = uiBuilder.createForm({
                fields: [
                    { type: 'input', id: 'generic-input', label: 'Generic' }
                ]
            });

            expect(html).toContain('generic-input');
        });

        test('routes radio type to createRadioGroup', () => {
            const html = uiBuilder.createForm({
                fields: [
                    {
                        type: 'radio',
                        name: 'gender',
                        label: 'Gender',
                        options: [
                            { value: 'male', label: 'Male' },
                            { value: 'female', label: 'Female' }
                        ]
                    }
                ]
            });

            expect(html).toContain('type="radio"');
            expect(html).toContain('Male');
            expect(html).toContain('Female');
        });

        test('routes checkbox type with options to createCheckboxGroup', () => {
            const html = uiBuilder.createForm({
                fields: [
                    {
                        type: 'checkbox',
                        name: 'conditions',
                        label: 'Conditions',
                        options: [
                            { value: 'htn', label: 'Hypertension' },
                            { value: 'dm', label: 'Diabetes' }
                        ]
                    }
                ]
            });

            expect(html).toContain('type="checkbox"');
            expect(html).toContain('Hypertension');
            expect(html).toContain('Diabetes');
        });

        test('routes checkbox type without options to createCheckbox', () => {
            const html = uiBuilder.createForm({
                fields: [
                    {
                        type: 'checkbox',
                        id: 'agree-cb',
                        label: 'I agree'
                    } as any
                ]
            });

            expect(html).toContain('type="checkbox"');
            expect(html).toContain('I agree');
            expect(html).toContain('agree-cb');
        });

        test('routes select type to createSelect', () => {
            const html = uiBuilder.createForm({
                fields: [
                    {
                        type: 'select',
                        id: 'unit-select',
                        label: 'Unit System',
                        options: [
                            { value: 'metric', label: 'Metric' },
                            { value: 'imperial', label: 'Imperial' }
                        ]
                    }
                ]
            });

            expect(html).toContain('<select');
            expect(html).toContain('Metric');
            expect(html).toContain('Imperial');
        });

        test('routes range type to createRange', () => {
            const html = uiBuilder.createForm({
                fields: [
                    {
                        type: 'range',
                        id: 'slider-input',
                        label: 'Severity',
                        min: 0,
                        max: 10,
                        step: 1,
                        defaultValue: 5
                    }
                ]
            });

            expect(html).toContain('type="range"');
            expect(html).toContain('slider-input');
        });

        test('routes section type to createSection', () => {
            const html = uiBuilder.createForm({
                fields: [
                    {
                        type: 'section',
                        title: 'Patient Demographics',
                        icon: 'P',
                        content: '<p>Enter patient info</p>'
                    }
                ]
            });

            expect(html).toContain('Patient Demographics');
            expect(html).toContain('Enter patient info');
        });

        test('unknown type returns empty string for that field', () => {
            const html = uiBuilder.createForm({
                fields: [
                    { type: 'unknown' as any, id: 'x', label: 'X' }
                ]
            });

            expect(html).toContain('<form');
            expect(html).not.toContain('unknown');
        });

        test('shows submit button when showSubmit is true', () => {
            const html = uiBuilder.createForm({
                fields: [],
                showSubmit: true,
                submitLabel: 'Compute'
            });

            expect(html).toContain('Compute');
            expect(html).toContain('type="submit"');
            expect(html).toContain('ui-button-primary');
        });

        test('uses default submitLabel when not specified', () => {
            const html = uiBuilder.createForm({
                fields: [],
                showSubmit: true
            });

            expect(html).toContain('Calculate');
        });

        test('hides submit button by default', () => {
            const html = uiBuilder.createForm({
                fields: []
            });

            expect(html).not.toContain('type="submit"');
        });

        test('renders multiple fields together', () => {
            const html = uiBuilder.createForm({
                fields: [
                    { type: 'number', id: 'age', label: 'Age' },
                    { type: 'text', id: 'name', label: 'Name' },
                    {
                        type: 'radio',
                        name: 'sex',
                        options: [
                            { value: 'm', label: 'M' },
                            { value: 'f', label: 'F' }
                        ]
                    }
                ]
            });

            expect(html).toContain('age');
            expect(html).toContain('name');
            expect(html).toContain('type="radio"');
        });
    });

    // =========================================================================
    // 3. createFormulaSection()
    // =========================================================================
    describe('createFormulaSection', () => {
        test('renders formula items with label and formula text', () => {
            const html = uiBuilder.createFormulaSection({
                items: [
                    { label: 'BMI', formula: 'weight / height^2' }
                ]
            });

            expect(html).toContain('ui-formula-section');
            expect(html).toContain('BMI');
            expect(html).toContain('weight / height^2');
            expect(html).toContain('Formulas');
        });

        test('uses title property as fallback for label', () => {
            const html = uiBuilder.createFormulaSection({
                items: [
                    { title: 'CrCl Formula', formula: '(140 - age) * weight / (72 * Cr)' }
                ]
            });

            expect(html).toContain('CrCl Formula');
        });

        test('uses content property as fallback for formula', () => {
            const html = uiBuilder.createFormulaSection({
                items: [
                    { label: 'Test', content: 'Some content text' }
                ]
            });

            expect(html).toContain('Some content text');
        });

        test('defaults label to "Formula" when neither label nor title provided', () => {
            const html = uiBuilder.createFormulaSection({
                items: [
                    { formula: 'x = y + z' }
                ]
            });

            expect(html).toContain('<strong>Formula:</strong>');
        });

        test('renders multiple formulas from formulas array', () => {
            const html = uiBuilder.createFormulaSection({
                items: [
                    {
                        label: 'Equations',
                        formulas: ['E = mc^2', 'F = ma', 'PV = nRT']
                    }
                ]
            });

            expect(html).toContain('E = mc^2');
            expect(html).toContain('F = ma');
            expect(html).toContain('PV = nRT');
        });

        test('renders notes when provided', () => {
            const html = uiBuilder.createFormulaSection({
                items: [
                    {
                        label: 'BSA',
                        formula: 'sqrt(height * weight / 3600)',
                        notes: 'Mosteller formula'
                    }
                ]
            });

            expect(html).toContain('ui-formula-notes');
            expect(html).toContain('Mosteller formula');
        });

        test('does not render notes element when notes not provided', () => {
            const html = uiBuilder.createFormulaSection({
                items: [
                    { label: 'Simple', formula: 'a + b' }
                ]
            });

            expect(html).not.toContain('ui-formula-notes');
        });

        test('hides title when hideTitle is true', () => {
            const html = uiBuilder.createFormulaSection({
                items: [{ formula: 'x' }],
                hideTitle: true
            });

            expect(html).not.toContain('Formulas');
            expect(html).toContain('ui-formula-section');
        });

        test('shows title by default', () => {
            const html = uiBuilder.createFormulaSection({
                items: [{ formula: 'x' }]
            });

            expect(html).toContain('ui-formula-title');
            expect(html).toContain('Formulas');
        });

        test('renders multiple items', () => {
            const html = uiBuilder.createFormulaSection({
                items: [
                    { label: 'A', formula: '1+1' },
                    { label: 'B', formula: '2+2' },
                    { label: 'C', formula: '3+3' }
                ]
            });

            expect(html).toContain('A');
            expect(html).toContain('B');
            expect(html).toContain('C');
            expect(html).toContain('1+1');
            expect(html).toContain('2+2');
            expect(html).toContain('3+3');
        });
    });

    // =========================================================================
    // 4. createCheckbox() (single checkbox)
    // =========================================================================
    describe('createCheckbox', () => {
        test('creates unchecked checkbox by default', () => {
            const html = uiBuilder.createCheckbox({
                id: 'cb-test',
                label: 'Enable feature'
            });

            expect(html).toContain('type="checkbox"');
            expect(html).toContain('id="cb-test"');
            expect(html).toContain('Enable feature');
            expect(html).toContain('value="1"');
            expect(html).not.toContain('checked');
        });

        test('creates checked checkbox when checked=true', () => {
            const html = uiBuilder.createCheckbox({
                id: 'cb-checked',
                label: 'Active',
                checked: true
            });

            expect(html).toContain('checked');
        });

        test('uses custom value', () => {
            const html = uiBuilder.createCheckbox({
                id: 'cb-val',
                label: 'Option',
                value: 'custom-val'
            });

            expect(html).toContain('value="custom-val"');
        });

        test('renders description text when provided', () => {
            const html = uiBuilder.createCheckbox({
                id: 'cb-desc',
                label: 'Terms',
                description: 'By checking this you agree to the terms'
            });

            expect(html).toContain('checkbox-description');
            expect(html).toContain('By checking this you agree to the terms');
        });

        test('does not render description when not provided', () => {
            const html = uiBuilder.createCheckbox({
                id: 'cb-nodesc',
                label: 'No description'
            });

            expect(html).not.toContain('checkbox-description');
        });

        test('has correct structure with ui-checkbox-option wrapper', () => {
            const html = uiBuilder.createCheckbox({
                id: 'struct-cb',
                label: 'Structure test'
            });

            container.innerHTML = html;
            const wrapper = container.querySelector('.ui-checkbox-option');
            expect(wrapper).not.toBeNull();
            const input = wrapper?.querySelector('input[type="checkbox"]');
            expect(input).not.toBeNull();
            const label = wrapper?.querySelector('label.checkbox-label');
            expect(label).not.toBeNull();
        });
    });

    // =========================================================================
    // 5. setRadioValue()
    // =========================================================================
    describe('setRadioValue', () => {
        test('sets radio to checked and dispatches change event', () => {
            container.innerHTML = `
                <div class="ui-radio-option">
                    <input type="radio" name="test-radio" value="a" id="r-a">
                    <label for="r-a">A</label>
                </div>
                <div class="ui-radio-option">
                    <input type="radio" name="test-radio" value="b" id="r-b">
                    <label for="r-b">B</label>
                </div>
            `;

            const changeHandler = jest.fn();
            const radioB = document.getElementById('r-b') as HTMLInputElement;
            radioB.addEventListener('change', changeHandler);

            uiBuilder.setRadioValue('test-radio', 'b');

            expect(radioB.checked).toBe(true);
            expect(changeHandler).toHaveBeenCalled();
        });

        test('does not throw when radio with given name/value does not exist', () => {
            container.innerHTML = `
                <input type="radio" name="existing" value="1">
            `;

            expect(() => {
                uiBuilder.setRadioValue('nonexistent', 'xyz');
            }).not.toThrow();
        });

        test('change event bubbles', () => {
            container.innerHTML = `
                <div id="wrapper">
                    <input type="radio" name="bubble-test" value="yes">
                </div>
            `;

            const bubbleHandler = jest.fn();
            const wrapper = document.getElementById('wrapper')!;
            wrapper.addEventListener('change', bubbleHandler);

            uiBuilder.setRadioValue('bubble-test', 'yes');

            expect(bubbleHandler).toHaveBeenCalled();
        });
    });

    // =========================================================================
    // 6. initializeComponents() deeper tests
    // =========================================================================
    describe('initializeComponents - deeper tests', () => {
        describe('Copy Report button', () => {
            let originalClipboard: Clipboard;

            beforeEach(() => {
                originalClipboard = navigator.clipboard;
            });

            afterEach(() => {
                Object.defineProperty(navigator, 'clipboard', {
                    value: originalClipboard,
                    writable: true,
                    configurable: true
                });
            });

            test('copy button calls navigator.clipboard.writeText with report', async () => {
                const writeTextMock = jest.fn<(text: string) => Promise<void>>().mockResolvedValue(undefined);
                Object.defineProperty(navigator, 'clipboard', {
                    value: { writeText: writeTextMock },
                    writable: true,
                    configurable: true
                });

                container.innerHTML = uiBuilder.createResultBox({ id: 'result-box' });

                // Add some content to generate a report from
                const inputGroup = document.createElement('div');
                inputGroup.className = 'ui-input-group';
                inputGroup.innerHTML = `
                    <label for="test-val">Test</label>
                    <input id="test-val" type="number" value="42">
                `;
                container.appendChild(inputGroup);

                uiBuilder.initializeComponents(container);

                const copyBtn = container.querySelector('.copy-report-btn') as HTMLButtonElement;
                expect(copyBtn).not.toBeNull();

                copyBtn.click();

                // Give the promise time to resolve
                await new Promise(resolve => setTimeout(resolve, 50));

                expect(writeTextMock).toHaveBeenCalled();
                const reportArg = writeTextMock.mock.calls[0][0] as string;
                expect(reportArg).toContain('--- INPUTS ---');
                expect(reportArg).toContain('--- RESULTS ---');
            });

            test('copy button shows "Copied!" text after successful copy', async () => {
                const writeTextMock = jest.fn<(text: string) => Promise<void>>().mockResolvedValue(undefined);
                Object.defineProperty(navigator, 'clipboard', {
                    value: { writeText: writeTextMock },
                    writable: true,
                    configurable: true
                });

                container.innerHTML = uiBuilder.createResultBox({ id: 'copy-test' });
                uiBuilder.initializeComponents(container);

                const copyBtn = container.querySelector('.copy-report-btn') as HTMLButtonElement;
                copyBtn.click();

                await new Promise(resolve => setTimeout(resolve, 50));

                // The text content should have been temporarily changed
                // (It may have already reverted if setTimeout fired, but we can check the mock was called)
                expect(writeTextMock).toHaveBeenCalledTimes(1);
            });

            test('copy button handles clipboard failure gracefully', async () => {
                const writeTextMock = jest.fn<(text: string) => Promise<void>>().mockRejectedValue(new Error('Permission denied'));
                Object.defineProperty(navigator, 'clipboard', {
                    value: { writeText: writeTextMock },
                    writable: true,
                    configurable: true
                });

                const alertMock = jest.spyOn(window, 'alert').mockImplementation(() => {});
                const consoleErrorMock = jest.spyOn(console, 'error').mockImplementation(() => {});

                container.innerHTML = uiBuilder.createResultBox({ id: 'fail-test' });
                uiBuilder.initializeComponents(container);

                const copyBtn = container.querySelector('.copy-report-btn') as HTMLButtonElement;
                copyBtn.click();

                await new Promise(resolve => setTimeout(resolve, 50));

                expect(consoleErrorMock).toHaveBeenCalledWith(
                    'Failed to copy report:',
                    expect.any(Error)
                );
                expect(alertMock).toHaveBeenCalledWith('Failed to copy report to clipboard');

                alertMock.mockRestore();
                consoleErrorMock.mockRestore();
            });
        });

        describe('Range slider value display', () => {
            test('updates value display when slider input event fires', () => {
                container.innerHTML = uiBuilder.createRange({
                    id: 'test-slider',
                    label: 'Volume',
                    min: 0,
                    max: 100,
                    defaultValue: 50,
                    unit: 'dB',
                    showValue: true
                });

                uiBuilder.initializeComponents(container);

                const slider = container.querySelector('#test-slider') as HTMLInputElement;
                const valueDisplay = container.querySelector('#test-slider-value') as HTMLSpanElement;

                expect(valueDisplay.textContent).toBe('50dB');

                // Simulate changing the slider
                slider.value = '75';
                slider.dispatchEvent(new Event('input'));

                expect(valueDisplay.textContent).toBe('75dB');
            });

            test('preserves unit text when updating slider value', () => {
                container.innerHTML = uiBuilder.createRange({
                    id: 'pct-slider',
                    label: 'Percentage',
                    min: 0,
                    max: 100,
                    defaultValue: 30,
                    unit: '%',
                    showValue: true
                });

                uiBuilder.initializeComponents(container);

                const slider = container.querySelector('#pct-slider') as HTMLInputElement;
                const valueDisplay = container.querySelector('#pct-slider-value') as HTMLSpanElement;

                slider.value = '85';
                slider.dispatchEvent(new Event('input'));

                expect(valueDisplay.textContent).toBe('85%');
            });

            test('works when showValue is false (no value display element)', () => {
                container.innerHTML = uiBuilder.createRange({
                    id: 'no-display',
                    label: 'Silent Slider',
                    min: 0,
                    max: 10,
                    defaultValue: 5,
                    showValue: false
                });

                expect(() => {
                    uiBuilder.initializeComponents(container);
                }).not.toThrow();

                // Value display should not exist
                const valueDisplay = container.querySelector('#no-display-value');
                expect(valueDisplay).toBeNull();
            });
        });

        describe('Radio visual feedback', () => {
            test('adds selected class to parent when radio is changed', () => {
                container.innerHTML = uiBuilder.createRadioGroup({
                    name: 'visual-radio',
                    label: 'Choose',
                    options: [
                        { value: 'a', label: 'Alpha' },
                        { value: 'b', label: 'Beta' }
                    ]
                });

                uiBuilder.initializeComponents(container);

                const radioA = container.querySelector('input[value="a"]') as HTMLInputElement;
                const radioB = container.querySelector('input[value="b"]') as HTMLInputElement;

                // Select radio A
                radioA.checked = true;
                radioA.dispatchEvent(new Event('change', { bubbles: true }));

                expect(radioA.parentElement?.classList.contains('selected')).toBe(true);
                expect(radioB.parentElement?.classList.contains('selected')).toBe(false);

                // Switch to radio B
                radioB.checked = true;
                radioB.dispatchEvent(new Event('change', { bubbles: true }));

                expect(radioA.parentElement?.classList.contains('selected')).toBe(false);
                expect(radioB.parentElement?.classList.contains('selected')).toBe(true);
            });
        });

        describe('Checkbox visual feedback', () => {
            test('adds selected class when checkbox is checked', () => {
                container.innerHTML = uiBuilder.createCheckboxGroup({
                    name: 'visual-cb',
                    label: 'Select',
                    options: [
                        { value: 'x', label: 'X' },
                        { value: 'y', label: 'Y' }
                    ]
                });

                uiBuilder.initializeComponents(container);

                const cbX = container.querySelector('input[value="x"]') as HTMLInputElement;

                // Check the checkbox
                cbX.checked = true;
                cbX.dispatchEvent(new Event('change'));

                expect(cbX.parentElement?.classList.contains('selected')).toBe(true);

                // Uncheck the checkbox
                cbX.checked = false;
                cbX.dispatchEvent(new Event('change'));

                expect(cbX.parentElement?.classList.contains('selected')).toBe(false);
            });

            test('initializes selected class for pre-checked checkboxes', () => {
                container.innerHTML = uiBuilder.createCheckboxGroup({
                    name: 'pre-cb',
                    label: 'Preselected',
                    options: [
                        { value: 'pre', label: 'Pre-checked', checked: true }
                    ]
                });

                uiBuilder.initializeComponents(container);

                const cb = container.querySelector('input[value="pre"]') as HTMLInputElement;
                expect(cb.checked).toBe(true);
                expect(cb.parentElement?.classList.contains('selected')).toBe(true);
            });
        });

        describe('Unit toggle initialization', () => {
            test('handles invalid JSON in data-unit-toggle gracefully', () => {
                const warnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});

                container.innerHTML = `
                    <div class="ui-input-wrapper" data-unit-toggle="not valid json">
                        <input class="ui-input" type="number">
                    </div>
                `;

                expect(() => {
                    uiBuilder.initializeComponents(container);
                }).not.toThrow();

                expect(warnSpy).toHaveBeenCalledWith(
                    'Failed to parse unit toggle config:',
                    expect.any(Error)
                );

                warnSpy.mockRestore();
            });
        });
    });

    // =========================================================================
    // 7. createList()
    // =========================================================================
    describe('createList', () => {
        test('creates unordered list by default', () => {
            const html = uiBuilder.createList({
                items: ['Apple', 'Banana', 'Cherry']
            });

            expect(html).toContain('<ul');
            expect(html).toContain('</ul>');
            expect(html).toContain('<li>Apple</li>');
            expect(html).toContain('<li>Banana</li>');
            expect(html).toContain('<li>Cherry</li>');
        });

        test('creates ordered list when type is ol', () => {
            const html = uiBuilder.createList({
                items: ['First', 'Second'],
                type: 'ol'
            });

            expect(html).toContain('<ol');
            expect(html).toContain('</ol>');
            expect(html).toContain('<li>First</li>');
        });

        test('includes className', () => {
            const html = uiBuilder.createList({
                items: ['Item'],
                className: 'custom-list'
            });

            expect(html).toContain('custom-list');
            expect(html).toContain('ui-list');
        });

        test('renders empty list when items is empty', () => {
            const html = uiBuilder.createList({
                items: []
            });

            expect(html).toContain('<ul');
            expect(html).toContain('</ul>');
            expect(html).not.toContain('<li>');
        });

        test('renders items with HTML content', () => {
            const html = uiBuilder.createList({
                items: ['<strong>Bold</strong>', '<em>Italic</em>']
            });

            expect(html).toContain('<strong>Bold</strong>');
            expect(html).toContain('<em>Italic</em>');
        });
    });

    // =========================================================================
    // 8. createReference()
    // =========================================================================
    describe('createReference', () => {
        test('renders reference section with default title and icon', () => {
            const html = uiBuilder.createReference({
                citations: ['Smith et al. 2020']
            });

            expect(html).toContain('Reference');
            expect(html).toContain('Smith et al. 2020');
            expect(html).toContain('info-section');
        });

        test('uses custom title', () => {
            const html = uiBuilder.createReference({
                title: 'Bibliography',
                citations: ['Ref 1']
            });

            expect(html).toContain('Bibliography');
        });

        test('uses custom icon', () => {
            const html = uiBuilder.createReference({
                citations: ['Ref 1'],
                icon: 'BOOK'
            });

            expect(html).toContain('BOOK');
        });

        test('renders multiple citations', () => {
            const html = uiBuilder.createReference({
                citations: [
                    'Jones A. JAMA 2019;321:1234-1240.',
                    'Lee B. Lancet 2020;395:100-110.',
                    'Garcia C. NEJM 2021;384:50-60.'
                ]
            });

            expect(html).toContain('Jones A. JAMA 2019');
            expect(html).toContain('Lee B. Lancet 2020');
            expect(html).toContain('Garcia C. NEJM 2021');

            // Each citation should be in its own <p> tag
            container.innerHTML = html;
            const paragraphs = container.querySelectorAll('p');
            expect(paragraphs.length).toBe(3);
        });

        test('renders with empty citations array', () => {
            const html = uiBuilder.createReference({
                citations: []
            });

            expect(html).toContain('Reference');
            expect(html).not.toContain('<p>');
        });
    });

    // =========================================================================
    // 9. createRiskFactorItem()
    // =========================================================================
    describe('createRiskFactorItem', () => {
        test('creates checkbox risk factor item by default', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-smoking',
                label: 'Current Smoker'
            });

            expect(html).toContain('type="checkbox"');
            expect(html).toContain('id="rf-smoking"');
            expect(html).toContain('Current Smoker');
            expect(html).toContain('risk-factor-item');
        });

        test('creates radio risk factor item', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-age',
                label: 'Age >= 75',
                type: 'radio',
                name: 'age-group'
            });

            expect(html).toContain('type="radio"');
            expect(html).toContain('name="age-group"');
        });

        test('renders checked state', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-checked',
                label: 'Pre-selected',
                checked: true
            });

            expect(html).toContain('checked');
        });

        test('renders bleeding HR badge when bleedingHR is not 1.0', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-bleed',
                label: 'Bleeding Factor',
                bleedingHR: 2.5
            });

            expect(html).toContain('hr-badge-bleeding');
            expect(html).toContain('Bleeding HR: 2.5');
        });

        test('does not render bleeding HR badge when bleedingHR is 1.0', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-bleed-1',
                label: 'No Badge',
                bleedingHR: 1.0
            });

            expect(html).not.toContain('hr-badge-bleeding');
        });

        test('does not render bleeding HR badge when bleedingHR is null', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-bleed-null',
                label: 'Null Badge',
                bleedingHR: null
            });

            expect(html).not.toContain('hr-badge-bleeding');
        });

        test('renders ischemic HR badge when ischemicHR is not 1.0', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-ischemic',
                label: 'Ischemic Factor',
                ischemicHR: 3.1
            });

            expect(html).toContain('hr-badge-ischemic');
            expect(html).toContain('Thrombotic HR: 3.1');
        });

        test('does not render ischemic HR badge when ischemicHR is 1.0', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-isch-1',
                label: 'No Thrombotic',
                ischemicHR: 1.0
            });

            expect(html).not.toContain('hr-badge-ischemic');
        });

        test('does not render ischemic HR badge when ischemicHR is null', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-isch-null',
                label: 'Null Thrombotic',
                ischemicHR: null
            });

            expect(html).not.toContain('hr-badge-ischemic');
        });

        test('renders both bleeding and ischemic badges', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-both',
                label: 'Dual Risk',
                bleedingHR: 1.8,
                ischemicHR: 2.2
            });

            expect(html).toContain('hr-badge-bleeding');
            expect(html).toContain('Bleeding HR: 1.8');
            expect(html).toContain('hr-badge-ischemic');
            expect(html).toContain('Thrombotic HR: 2.2');
        });

        test('renders data-factor-id attribute', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-data',
                label: 'Data Factor',
                dataFactorId: 'factor-123'
            });

            expect(html).toContain('data-factor-id="factor-123"');
        });

        test('does not render data-factor-id when not provided', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-nodata',
                label: 'No Data Attr'
            });

            expect(html).not.toContain('data-factor-id');
        });

        test('does not render name attribute when not provided', () => {
            const html = uiBuilder.createRiskFactorItem({
                id: 'rf-noname',
                label: 'No Name'
            });

            expect(html).not.toContain('name=');
        });
    });

    // =========================================================================
    // 10. createRiskFactorGroup()
    // =========================================================================
    describe('createRiskFactorGroup', () => {
        test('renders group title', () => {
            const html = uiBuilder.createRiskFactorGroup({
                title: 'Patient Factors',
                items: [
                    { id: 'pf-1', label: 'Factor 1' }
                ]
            });

            expect(html).toContain('Patient Factors');
            expect(html).toContain('factor-group-title');
        });

        test('renders group title with icon', () => {
            const html = uiBuilder.createRiskFactorGroup({
                title: 'Bleeding Risks',
                icon: 'ICON',
                items: [
                    { id: 'br-1', label: 'Risk 1' }
                ]
            });

            expect(html).toContain('ICON');
            expect(html).toContain('Bleeding Risks');
        });

        test('renders group without icon', () => {
            const html = uiBuilder.createRiskFactorGroup({
                title: 'No Icon Group',
                items: [
                    { id: 'ni-1', label: 'Item 1' }
                ]
            });

            // Title should be present without leading icon space
            expect(html).toContain('No Icon Group');
        });

        test('delegates items to createRiskFactorItem', () => {
            const html = uiBuilder.createRiskFactorGroup({
                title: 'Multi Group',
                items: [
                    { id: 'mg-1', label: 'Item A', bleedingHR: 1.5 },
                    { id: 'mg-2', label: 'Item B', ischemicHR: 2.0 },
                    { id: 'mg-3', label: 'Item C', type: 'radio', name: 'mg-radio' }
                ]
            });

            expect(html).toContain('Item A');
            expect(html).toContain('Item B');
            expect(html).toContain('Item C');
            expect(html).toContain('Bleeding HR: 1.5');
            expect(html).toContain('Thrombotic HR: 2');
            expect(html).toContain('type="radio"');
            expect(html).toContain('name="mg-radio"');

            // Should contain three risk-factor-item divs
            container.innerHTML = html;
            const items = container.querySelectorAll('.risk-factor-item');
            expect(items.length).toBe(3);
        });

        test('renders group with empty items array', () => {
            const html = uiBuilder.createRiskFactorGroup({
                title: 'Empty Group',
                items: []
            });

            expect(html).toContain('Empty Group');
            expect(html).toContain('factor-group-title');
            // No risk factor items
            container.innerHTML = html;
            const items = container.querySelectorAll('.risk-factor-item');
            expect(items.length).toBe(0);
        });
    });

    // =========================================================================
    // 11. Edge case: createAlert with escapeMessage
    // =========================================================================
    describe('createAlert - escapeMessage', () => {
        test('escapes HTML when escapeMessage is true', () => {
            const html = uiBuilder.createAlert({
                type: 'warning',
                message: '<script>alert("xss")</script>',
                escapeMessage: true
            });

            expect(html).not.toContain('<script>');
            expect(html).toContain('&lt;script&gt;');
        });

        test('does not escape HTML when escapeMessage is false', () => {
            const html = uiBuilder.createAlert({
                type: 'info',
                message: '<strong>Bold text</strong>',
                escapeMessage: false
            });

            expect(html).toContain('<strong>Bold text</strong>');
        });

        test('default icon for warning type', () => {
            const html = uiBuilder.createAlert({
                type: 'warning',
                message: 'Warning message'
            });

            expect(html).toContain('ui-alert-warning');
        });
    });

    // =========================================================================
    // 12. createTable with stickyFirstColumn
    // =========================================================================
    describe('createTable - stickyFirstColumn', () => {
        test('adds sticky-col class to first column cells', () => {
            const html = uiBuilder.createTable({
                headers: ['Name', 'Value'],
                rows: [['A', '1'], ['B', '2']],
                stickyFirstColumn: true
            });

            expect(html).toContain('sticky-col');
            expect(html).toContain('has-sticky-col');

            container.innerHTML = html;
            const stickyHeaders = container.querySelectorAll('th.sticky-col');
            expect(stickyHeaders.length).toBe(1);
            const stickyCells = container.querySelectorAll('td.sticky-col');
            expect(stickyCells.length).toBe(2);
        });

        test('does not add sticky-col when stickyFirstColumn is false', () => {
            const html = uiBuilder.createTable({
                headers: ['Name', 'Value'],
                rows: [['A', '1']],
                stickyFirstColumn: false
            });

            container.innerHTML = html;
            const stickyCells = container.querySelectorAll('.sticky-col');
            // All cells have class="" (empty) but the attribute is there
            // Let's check by text content
            expect(html).not.toContain('has-sticky-col');
        });

        test('includes table id when provided', () => {
            const html = uiBuilder.createTable({
                id: 'my-table',
                headers: ['H'],
                rows: [['R']]
            });

            expect(html).toContain('id="my-table"');
        });

        test('includes custom className', () => {
            const html = uiBuilder.createTable({
                headers: ['H'],
                rows: [],
                className: 'striped-table'
            });

            expect(html).toContain('striped-table');
        });
    });

    // =========================================================================
    // 13. createSection - subtitle
    // =========================================================================
    describe('createSection - subtitle', () => {
        test('renders subtitle when provided', () => {
            const html = uiBuilder.createSection({
                title: 'Main Title',
                subtitle: 'Subtitle text',
                content: '<p>Body</p>'
            });

            expect(html).toContain('ui-section-subtitle');
            expect(html).toContain('Subtitle text');
        });

        test('does not render subtitle when not provided', () => {
            const html = uiBuilder.createSection({
                title: 'Title Only',
                content: '<p>Body</p>'
            });

            expect(html).not.toContain('ui-section-subtitle');
        });

        test('renders section without title', () => {
            const html = uiBuilder.createSection({
                content: '<p>Content only</p>'
            });

            expect(html).not.toContain('ui-section-title');
            expect(html).toContain('Content only');
        });
    });

    // =========================================================================
    // 14. UIBuilder class export and singleton
    // =========================================================================
    describe('UIBuilder class', () => {
        test('can create a custom instance', () => {
            const builder = new UIBuilder();
            const html = builder.createSection({
                title: 'Custom Instance',
                content: '<p>Works</p>'
            });

            expect(html).toContain('Custom Instance');
        });

        test('singleton instance is available', () => {
            expect(uiBuilder).toBeInstanceOf(UIBuilder);
        });
    });
});
