// js/calculators/index.js

// This is a static list of metadata, not imported modules.
// This prevents a syntax error in one calculator from breaking the entire app.
export const calculatorModules = [
    { id: '2helps2b', title: '2HELPS2B Score for Seizure Risk' },
    { id: '4as-delirium', title: '4 A\'s Test for Delirium' },
    { id: '4c-mortality-covid', title: '4C Mortality Score for COVID-19' },
    { id: '4peps', title: '4PEPS Score for Post-Encephalitic Parkinsonism' },
    { id: '4ts-hit', title: '4Ts Score for Heparin-Induced Thrombocytopenia (HIT)' },
    { id: '6mwd', title: '6-Minute Walk Distance (6MWD) Calculator' },
    { id: 'abl', title: 'ABL90 FLEX Analyzer Calculator' },
    { id: 'abg-analyzer', title: 'ABG Analyzer' },
    { id: 'action-icu', title: 'ACTION-ICU Risk Score for Post-cardiac Arrest Mortality' },
    { id: 'af-risk', title: 'Atrial Fibrillation (AF) Risk Score (CHADs2-VASc & HAS-BLED)' },
    { id: 'apache-ii', title: 'APACHE II Score' },
    { id: 'apgar', title: 'APGAR Score' },
    { id: 'ariscat', title: 'ARISCAT Score for Postoperative Pulmonary Complications' },
    { id: 'ascvd', title: 'ASCVD Risk Score (10-Year)' },
    { id: 'bacterial-meningitis-score', title: 'Bacterial Meningitis Score for Children' },
    { id: 'benzo-conversion', title: 'Benzodiazepine Conversion Calculator' },
    { id: 'bmi-bsa', title: 'BMI and BSA Calculator' },
    { id: 'bwps', title: 'BWPS for Thyrotoxicosis' },
    { id: 'calcium-correction', title: 'Corrected Calcium for Hypoalbuminemia' },
    { id: 'caprini', title: 'Caprini Score for VTE Risk' },
    { id: 'centor', title: 'Centor Score for Strep Pharyngitis' },
    { id: 'charlson', title: 'Charlson Comorbidity Index (CCI)' },
    { id: 'child-pugh', title: 'Child-Pugh Score for Cirrhosis Mortality' },
    { id: 'ciwa-ar', title: 'CIWA-Ar for Alcohol Withdrawal' },
    { id: 'ckd-epi', title: 'CKD-EPI GFR (2021)' },
    { id: 'cpis', title: 'Clinical Pulmonary Infection Score (CPIS) for VAP' },
    { id: 'crcl', title: 'Cockcroft-Gault Creatinine Clearance' },
    { id: 'curb-65', title: 'CURB-65 Score for Pneumonia Severity' },
    { id: 'dasi', title: 'Duke Activity Status Index (DASI)' },
    { id: 'due-date', title: 'Due Date Calculator' },
    { id: 'ethanol-concentration', title: 'Ethanol Concentration Conversion' },
    { id: 'ett', title: 'ETT Depth and Tidal Volume Calculator' },
    { id: 'fena', title: 'Fractional Excretion of Sodium (FENa)' },
    { id: 'fib-4', title: 'FIB-4 Score for Liver Fibrosis' },
    { id: 'free-water-deficit', title: 'Free Water Deficit in Hypernatremia' },
    { id: 'gad-7', title: 'GAD-7 for Anxiety' },
    { id: 'garfield-af', title: 'GARFIELD-AF Risk Score' },
    { id: 'gcs', title: 'Glasgow Coma Scale (GCS)' },
    { id: 'geneva-score', title: 'Geneva Score (Revised) for Pulmonary Embolism' },
    { id: 'grace-acs', title: 'GRACE ACS Risk Score' },
    { id: 'gupta-mica', title: 'Gupta Perioperative Cardiac Risk (MICA)' },
    { id: 'gwtg-hf', title: 'GWTG-HF Risk Score' },
    { id: 'has-bled', title: 'HAS-BLED Score for Major Bleeding Risk' },
    { id: 'heart-score', title: 'HEART Score for Major Cardiac Events' },
    { id: 'homa-ir', title: 'HOMA-IR for Insulin Resistance' },
    { id: 'hscore', title: 'HScore for Hemophagocytic Lymphohistiocytosis (HLH)' },
    { id: 'ibw', title: 'Ideal Body Weight (IBW) Calculator' },
    { id: 'intraop-fluid', title: 'Intraoperative Fluid Dosing Calculator' },
    { id: 'isth-dic', title: 'ISTH Criteria for DIC' },
    { id: 'kawasaki', title: 'Kawasaki Disease Diagnostic Criteria' },
    { id: 'ldl', title: 'Friedewald Equation for LDL Cholesterol' },
    { id: 'maintenance-fluids', title: 'Maintenance Fluids Calculator' },
    { id: 'maggic', title: 'MAGGIC Risk Calculator for Heart Failure' },
    { id: 'map', title: 'Mean Arterial Pressure (MAP)' },
    { id: 'mdrd-gfr', title: 'MDRD GFR Equation' },
    { id: 'meld-na', title: 'MELD-Na Score for Liver Disease Severity' },
    { id: 'mme', title: 'Morphine Milligram Equivalent (MME) Calculator' },
    { id: 'nafld-fibrosis-score', title: 'NAFLD Fibrosis Score' },
    { id: 'nihss', title: 'NIH Stroke Scale (NIHSS)' },
    { id: 'padua-vte', title: 'Padua Prediction Score for VTE Risk' },
    { id: 'pecarn', title: 'PECARN Head Trauma Rule for Children' },
    { id: 'perc', title: 'PERC Rule for Pulmonary Embolism' },
    { id: 'phenytoin-correction', title: 'Corrected Phenytoin for Hypoalbuminemia' },
    { id: 'phq-9', title: 'PHQ-9 for Depression' },
    { id: 'prevent-cvd', title: 'QRISK3-Based CVD Risk (UK)' },
    { id: 'qsofa', title: 'qSOFA Score for Sepsis' },
    { id: 'qtc', title: 'Corrected QT Interval (QTc)' },
    { id: 'ranson', title: 'Ranson Criteria for Pancreatitis Mortality' },
    { id: 'rcri', title: 'Revised Cardiac Risk Index (RCRI)' },
    { id: 'regiscar', title: 'RegiSCAR Score for DRESS' },
    { id: 'score2-diabetes', title: 'SCORE2-Diabetes for 10-Year CVD Risk' },
    { id: 'serum-anion-gap', title: 'Serum Anion Gap' },
    { id: 'serum-osmolality', title: 'Serum Osmolality' },
    { id: 'sex-shock', title: 'SEX-SHOCK Risk Score for Cardiogenic Shock' },
    { id: 'sirs', title: 'SIRS Criteria for Systemic Inflammatory Response' },
    { id: 'sodium-correction', title: 'Corrected Sodium for Hyperglycemia' },
    { id: 'sofa', title: 'SOFA Score for Sepsis Organ Failure' },
    { id: 'steroid-conversion', title: 'Corticosteroid Conversion Calculator' },
    { id: 'stop-bang', title: 'STOP-BANG for Obstructive Sleep Apnea' },
    { id: 'timi-nstemi', title: 'TIMI Risk Score for UA/NSTEMI' },
    { id: 'tpa-dosing-stroke', title: 'tPA Dosing for Acute Stroke' },
    { id: 'tpa-dosing', title: 'tPA Dosing for PE and MI' },
    { id: 'ttkg', title: 'Transtubular Potassium Gradient (TTKG)' },
    { id: 'wells-dvt', title: 'Wells Criteria for DVT' },
    { id: 'wells-pe', title: 'Wells Criteria for PE' }
].sort((a, b) => a.title.localeCompare(b.title));
