export declare function getMostRecentObservation(client: any, code: string): Promise<any>;
export declare function getObservationValue(observation: any, code?: string): number | null;
export declare function calculateAge(birthDate: string): number;
export declare function displayPatientInfo(client: any, patientInfoDiv: HTMLElement): Promise<any>;
export declare function getPatientConditions(client: any, codes: string[]): Promise<any[]>;
export declare function getPatient(client: any): Promise<any>;
export declare function getObservation(client: any, code: string): Promise<any>;
export declare function convertToMmolL(value: number, type: string): number;
export declare function convertToMgDl(value: number, type: string): number;
export declare function getMedicationRequests(client: any, rxnormCodes: string[]): Promise<any[]>;
export declare const UNIT_CONVERSIONS: any;
export declare function convertUnit(value: number, fromUnit: string, toUnit: string, measurementType: string): number | null;
export declare function createUnitSelector(inputId: string, measurementType: string, units: string[], defaultUnit?: string): string;
export declare function initializeUnitConversion(container: HTMLElement, inputId: string, onChangeCallback?: () => void): () => void;
export declare function getValueInStandardUnit(container: HTMLElement, inputId: string, standardUnit: string): number | null;
export declare function initializeSegmentedControls(container: HTMLElement): void;
